# Generated by Django 5.2 on 2026-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_action_trigger_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description_format',
            field=models.CharField(choices=[('raw', 'Plain text'), ('html', 'HTML'), ('markdown', 'Markdown'), ('jira_wiki', 'Jira Wiki Markup')], default='raw', help_text='Format of the description field in the incoming payload.', max_length=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='field_mappings',
            field=models.JSONField(help_text='Map ticket fields to JSONPath expressions or literal values. Supported keys: key, title, description, type, priority, category, creator, service, sub_service. Example: {"key": "$.issue.key", "title": "$.issue.fields.summary", "description": "$.issue.fields.description", "type": "incident", "priority": "medium"}'),
        ),
    ]
