# Generated by Django 5.2 on 2026-07-04 16:04

from django.db import migrations, models


def backfill_terminal_statuses(apps, schema_editor):
    JiraStatusConfig = apps.get_model('settings_hub', 'JiraStatusConfig')
    JiraStatusConfig.objects.filter(status_name__iexact='done').update(is_terminal=True)
    JiraStatusConfig.objects.filter(status_name__iexact='descartado').update(is_terminal=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0002_jirastatusconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirastatusconfig',
            name='is_terminal',
            field=models.BooleanField(default=False, verbose_name='Closed Status'),
        ),
        migrations.RunPython(backfill_terminal_statuses, noop),
    ]
