# Generated by Django 5.2 on 2026-08-27 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0007_jiraticket_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraevent',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
