# Generated by Django 5.2 on 2026-07-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_container_credential_container_containeraccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialversion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
