# Generated by Django 5.2 on 2026-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_move_team_to_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH Key'), ('certificate', 'Certificate'), ('api_key', 'API Key'), ('secret', 'Secret')], max_length=20),
        ),
    ]
