# Generated by Django 5.2 on 2026-07-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0005_report_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='timezone',
            field=models.CharField(default='America/Argentina/Cordoba', max_length=64),
        ),
    ]
